#!/usr/bin/env bash
# A script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script
sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  frimpong-frontend
        bind *:80
        mode http
        default_backend frimpong-backend
backend frimpong-backend
        balance roundrobin
        server 164183-web-01 52.91.144.93:80 check
        server 164183-web-02 54.236.41.73:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
