#!/usr/bin/env bash
#debugging Failed to connect to 0 port 80
#I use the combination s ansd f flag to to create symbolic link and delete 
#the existing sites-availabe and sites-enabled
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
