#!/usr/bin/env bash
# Displays hours from 0 to 12 and minutes from 1 to 59

hours=0

while [ $hours -lt 13 ]; do
	echo "hours: $hours"
	i=1
	while [ $i -le 59 ]; do
		echo "$i"
		i=$((i+1))
	done
	hours=$((hours+1))
done
