#!/usr/bin/env bash
# A script that fixes an apache server in a container
docker run -p 8080:80 -d -it holbertonschool/265-0
docker exec -it <container_id> /bin/bash
vi /etc/apache2/sites-enabled/000-default.conf
DocumentRoot /var/www/html/public
mkdir /var/www/html/public
echo "Hello Holberton" > /var/www/html/public/index.html
service apache2 start
